cmd/gokr-packer/gotool.go
`gokr-packer` specifies `GOARCH=arm64` and `CGO_ENABLED=0`. It should also specify `GOOS=linux` to enable use of e.g. `gokr-packer -update` from non-Linux hosts.
=> Also specify GOOS

cmd/gokr-packer/cacerts_darwin.go, cmd/gokr-packer/cacerts_linux.go, cmd/gokr-packer/packer.go
This is one step towards making `gokr-packer` work on macOS systems.
=> Find macOS Homebrew CA certs

cmd/gokr-packer/parttable_darwin.go
This change makes it possible to use the combination of gokr-packer and
image manipulation tools like balena Ethcer on macOS.
=> cmd/gokr-packer: add missing rereadPartitions for darwin

cmd/gokr-packer/certs.go, cmd/gokr-packer/packer.go, cmd/gokr-updater/updater.go, go.mod, go.sum
This PR adds a `-tls` option to the packer, which
1. Generates a self-signed certificate if `-tls=self-signd`
2. Packs the certificate into the image (`/etc/ssl/web.pem` and `/etc/ssl/web_key.pem`)
The updater pins the generated certificate in the local configuration and implements TLS stripping detection. Certificates can be pinned manually by placing them into the host specific configuration directory. Depends on [my pr for internal](https://github.com/gokrazy/internal/pull/4).
=> Packer part of gokrazy/gokrazy#7

README.md
This is a minor update to have correct command and ignore the `-t vfat` as the root partition is `ext4`.
Tested this command on one of the image built from gokr-packer on Fedora 33
=> Updating to have correct command for mounting root

cmd/gokr-packer/packer.go
This fixes the URL displayed when custom ports are configured.
Final missing piece I don't now how to get correct: persist host/port settings and read back if `update=yes`.
=> Print correct uri when http(s)_port ist used

cmd/gokr-packer/gotool.go, cmd/gokr-packer/packer.go
Fix https://github.com/gokrazy/gokrazy/issues/80
Doing something like 
-build_args "-tags=release -ldflags '-X "github.com/andig/evcc/server.Version=foo" -X "github.com/andig/evcc/server.Commit=bar"'"
seems to work fine. I had expected needing to use something like https://github.com/kballard/go-shellquote or https://github.com/google/shlex but that doesn't seem required.
=> Support custom build args

cmd/gokr-packer/packer.go
Allows easy creating of perm partition when making image files.
=> Add mkfs.ext4 instructions with --overwrite mode

cmd/gokr-packer/packer.go, cmd/gokr-packer/write.go
This changes adds support to add extra files to the rootfs.
The definition is done similar to the flags, buildflags and env.
All files in the directory
```
./extrafiles/github.com/test/package/
```
will be added to the rootfs in
```
/
```
Currently it is not supported to overwrite files!
Here an example output for some extra files in `extrafiles/github.com/gokrazy/breakglass`:
```
2021/06/22 22:16:05 packer.go:670: package github.com/gokrazy/breakglass:
2021/06/22 22:16:05 packer.go:672:   will be started with command-line flags
2021/06/22 22:16:05 packer.go:674:     from flags/github.com/gokrazy/breakglass/flags.txt
2021/06/22 22:16:05 packer.go:676:     last modified: 2021-06-20T11:29:39+02:00 (58h46m26s ago)
2021/06/22 22:16:05 packer.go:672:   will include extra files in the root file …
```
=> Custom extra files for rootfs

cmd/gokr-packer/write.go
Don't accidentally pick up firmware files from CWD if -firmware_package is unset.
=> packer: ignore firmware globs if -firmware_package is empty

cmd/gokr-packer/packer.go, cmd/gokr-packer/write.go, go.mod, go.sum, packer/packer.go
Related to https://github.com/gokrazy/gokrazy/issues/101 and https://github.com/gokrazy/gokrazy/pull/102
Some ARM devices (like Odroid XU4/HC1/HC2) only support MBR booting.
Allow generating MBR partition table for such devices.
gokr-packer now supports a TOML device manifest that can specify details
like MBR partition table, list of kernel files and any additional blobs
that need to be stored on disk.
=> packer: allow using MBR partition tables

cmd/gokr-packer/buildinit.go, cmd/gokr-packer/packer.go, go.mod, go.sum
This PR adds a configuration `dontstart` it is related to https://github.com/gokrazy/gokrazy/pull/105.
This allows wait for the clock to be synced before starting the service
packer.go: adds `findWaitForClock()` function similar to `findDontStart()`
buildinit.go: adds an exclusive condition with don't start and start to run ~~`NewDelayedService()`~~ `NewWaitForClockService()`
=> packer: implement waitforclock per-package config files

go.mod, go.sum
Required for https://github.com/gokrazy/gokrazy/pull/108 to pass tests (to pick up https://github.com/gokrazy/internal/pull/11)
=> Update github.com/gokrazy/internal version

packer/packer.go
I (stupidly) tried to run packer on a SD card of 512MB. Everything looked fine, but nothing worked...
This PR adds a check that the device has enough capacity and fails otherwise:
```
device is too small (1100 MB needed, 488 MB available)
```
The check is not overly accurate (it actually needs a couple bytes more), but I think it will cover the vast majority of usecases.
=> packer: fail on small device

cmd/gok/cmd/logs.go, cmd/gok/cmd/run.go, go.mod, go.sum
Also this fixes `gok run` building anything at all.
Looking at `packer.Build` in its current version, it just isn't suited to "build current directory" it seems. Or at least I could not find any way to get it to build local packages (such as `.` or `./package`) no matter what I tried to pass to it from the `gok run` code. (I fully expect this to not just get merged as I put it, but rather invite a discussion on the correct way to fix `gok run`)
=> Use shared helper to build http client for log and run

cmd/gokr-packer/packer.go, packer/packer.go
When creating a disk image, `gokr-packer` shows an `mkfs.ext4` command to create the filesystem for `/perm`
```ShellSession
$ gokr-packer -overwrite gokrazy.img -target_storage_bytes 1258299392 github.com/gokrazy/hello
...
If your applications need to store persistent data, create a file system using e.g.:
/sbin/mkfs.ext4 gokrazy.img -F -E offset=1157627904
```
This will overwrite the secondary GPT at the end of the disk image.  
```ShellSession
$ /opt/homebrew/opt/e2fsprogs/sbin/mkfs.ext4 -F -E offset=1157627904 gokrazy.img
...
Writing superblocks and filesystem accounting information: done
```
```ShellSession
$ /opt/homebrew/opt/util-linux/sbin/fdisk -l gokrazy.img 
The backup GPT table is corrupt, but the primary appears OK, so that will be used.
...
```
=> Pass fs-size to mkfs.ext4 so it doesn't scribble over secondary GPT

internal/packer/parttable.go
From the commit message:
```
Without passing $HOME into the `sudo` invocation the instance parent directory detection
(https://github.com/gokrazy/internal/blob/main/instanceflag/instanceflag.go#L19) fails:
$ gok -i test overwrite --full /dev/sdc
[..]
2023/01/25 22:13:04 partitioning /dev/sdc (GPT + Hybrid MBR)
2023/01/25 22:13:04 Using sudo to gain permission to format /dev/sdc
2023/01/25 22:13:04 If you prefer, cancel and use: sudo setfacl -m u:${USER}:rw /dev/sdc
2023/01/25 22:13:04 open os.UserHomeDir failed: $HOME is not defined/gokrazy/test/config.json: no such file or directory
2023/01/25 22:13:04 exit status 1
This commit does the necessary passing.
```
While the attached commit fixes the immediate issue I'm not sure it's the right fix, so please do make suggestions if you have …
=> parttable: pass HOME env var to sudo

internal/gok/overwrite.go, internal/gok/sbom.go, internal/gok/update.go, internal/oldpacker/oldpacker.go, internal/packer/gaf.go, internal/packer/packer.go, internal/packer/sbom.go
It adds support within gok overwrite for the `gaf` output format.
`gaf` is the new gokrazy archive format output type.
It is immagined for storage and upgrade purposes.
A single, uncompressed zip archive file that contains:
- the MBR image (mbr.img)
- the boot image (boot.img)
- the root image (root.img)
- the SBOM of the gokrazy build (sbom.json)
It is lighter in size than a "full" disk image (it doesn't have the
partition filling bits).
It contains all the necessary bits to upgrade a gokrazy instance (all it
takes is the 3 imgs).
It can be directly accessed for a single file extraction (non compressed
zip property).
It can be easily unarchived by gokrazy appliances (cheap unzipping).
It is easy to verify what the build contains (SBOM alongside to be read).
Users can now generate a gaf …
=> gok overwrite: add gaf (gokrazy archive format) output

packer/gotool.go
I saw the following log, where the package and extrafiles are mixed up:
```
Including extra files for Go packages:
github.com/oliverpool/grafana-armv6
will include extra files in the root file system
from extrafiles/github.com/oliverpool/grafana-armv6
last modified: 2023-03-01T22:25:30+01:00 (454h57m51s ago)
tailscale.com/cmd/tailscaled
will include extra files in the root file system
from /home/olivier/go/pkg/mod/github.com/oliverpool/grafana-armv6@v1.0.3-v8.5.21/_gokrazy/extrafiles
last modified: 2023-03-01T21:14:00+01:00 (456h9m20s ago)
```
This sounded like a concurrency issue, and sure enough the `packer.PackageDirs` function does not return the dirs in the same order as the argument, as expected by (note the `idx`):
https://github.com/gokrazy/tools/blob/69473ec010f406f8125665ff28f2bd …
=> fix: prevent race condition in PackageDirs

internal/packer/packer.go
An issue has been reported regarding the wrong target arch, by @brutella : https://github.com/gokrazy-community/kernel-rpi-os-32/issues/4
```
target architecture "arm64" doesn't match the github.com/gokrazy-community/kernel-rpi-os-32/dist kernel type "arm"
```
Adding `GOARCH=arm` fixed the issue.
This PR adds a hint to the error message, to look for GOARCH:
```
target architecture "arm64" (GOARCH) doesn't match the github.com/gokrazy-community/kernel-rpi-os-32/dist kernel type "arm"
```
Introduced by https://github.com/gokrazy/gokrazy/issues/191 and https://github.com/gokrazy/tools/pull/54
=> gok: improve the error message for wrong target arch

go.mod, go.sum, internal/packer/packer.go, internal/packer/parttable.go, internal/packer/sbom.go
Currently SBOMs may have inconsistent hashing of the configuration file.
The representation of the config file in fact may differ at certain stages of the gok commands lifecycle, where at packer running time for example, extra InternalCompatibilityFlags would be added in memory (while that not being the case at `gok sbom` time), resulting in a differing config and as such differing SBOM hashes. The same would happen due to the differing pointer addresses in the config that resulted in differing hashing results.
This is now fixed by removing the InternalCompatibilityFlags from the config prior to its hashing, as well as converting the config into a string before performing the hash computation, to avoid hashing pointers problems.
=> Fix SBOM generation inconsistency

internal/packer/write.go
This achieves two things:
- It refactors the glob copy function such that it can actually handle sub-directories correctly (by copying using relative paths as opposed to always stripping the entire path away)
- It adds `overlays/*.dtbo` to the globs to copy overlays from the kernel package (if present)
Future things this PR is not meant to address (but will be useful in the future imo):
- Configuration to include overlays using the stock kernel package
- Configuration to adjust `config.txt` to add `dtoverlay` lines
=> Add ability to have sub-path globs and include overlays

go.sum
Looks like in #61 I forgot to rerun `go mod tidy`.
So here it is.
=> fix: rerun go mod tidy

internal/gok/overwrite.go, internal/gok/sbom.go, internal/gok/update.go, internal/oldpacker/oldpacker.go, internal/packer/gaf.go, internal/packer/packer.go, internal/packer/sbom.go
Builds on top of #65 
Fixes #64 
by adopting [approach 1](https://github.com/gokrazy/tools/issues/64#issuecomment-1772664940).
Seems to be working well for all the commands I tested: sbom, update, overwrite (full,gaf).
Testing:
```
$ make gaf 2>&1 >/dev/null
$ unzip -p /tmp/disk.gaf sbom.json | jq -r '.sbom_hash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9
$ make sbom | jq -r '.sbom_hash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9
$ make overwrite 2>&1 >/dev/null # creates a full.img
$ make test & # launches a qemu test machine from the full.img at (192.168.64.2)
$ curl -sL -H 'Accept: application/json' "http://gokrazy:$PASS@192.168.64.2/" | jq -r '.SBOMHash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9
$ make update
$ curl …
```
=> Fix SBOM generation inconsistency, take 2

internal/packer/write.go
Paired with https://github.com/gokrazy/firmware/pull/309
=> Copy .dtbo overlays from firmware repo as well

go.mod, go.sum, internal/oldpacker/oldpacker.go, internal/packer/packer.go, internal/packer/write.go, packer/packer.go
Support devices that require non-default space before the first partition starts (4MiB). Required to enable booting Rock64 devices
Related to https://github.com/gokrazy/gokrazy/issues/270
=> Support non-default FirstPartitionOffsetSectors

internal/packer/parttable.go
In gokrazy/gokrazy#222, it was mentioned that GOKRAZY_PARENT_DIR doesn't fully work for `gok overwrite`. I tracked this down to the point where sudo is used to elevate permissions, the environment is explicitly constructed and this variable needs to be included.
Before:
```
>> env GOKRAZY_PARENT_DIR=/home/vil/code/infrastructure gok -i dns overwrite --full=/dev/sdc
gokrazy gok g41f11f on GOARCH=amd64 GOOS=linux
Build target: CGO_ENABLED=0 GOARCH=arm64 GOOS=linux
Build timestamp: 2025-01-19T15:57:52-05:00
Loading system CA certificates from /etc/ssl/certs/ca-certificates.crt
Building 6 Go packages:
…
2025/01/19 15:57:58 partitioning /dev/sdc (GPT + Hybrid MBR)
2025/01/19 15:57:58 Using sudo to gain permission to format /dev/sdc
2025/01/19 15:57:58 If you prefer, cancel and use: sudo …
```
=> Preserve GOKRAZY_PARENT_DIR when executing sudo

go.mod, go.sum
Upgrade the fallback CA certs used when running gok on non-Linux platform. This is the Mozilla CA Certs list bundled as a  module that must be kept up to date. (Also the gok binary should be rebuilt).
=> packer: upgrade fallback Root CA certificates (Go module breml/rootcerts)

internal/packer/parttable.go
When acquiring access to partition the device, show message about use of "setfacl" only on Linux. Not on Darwin where it is irrelevant.
=> overwrite: show setfacl suggestion only on Linux
